### ISSUE TITLE
Could Firefox somehow be added to have Mica effect?

### ISSUE THREAD

**Issue by Void48** [minusium/MicaForEveryone#10]
https://www.reddit.com/r/firefox/comments/q95cw5/firefox_with_mica_material_a_proof_of_concept/

**Comment by minusium** [comment]
Well this app only works on native titlebar, while Firefox uses a custom titlebar. This app doesn't work on VIsual Studio and Chrome neither and it's not designed to work there. Maybe it's possible to write another app that does that, maybe a dll hook to be injected to Firefox, or a Firefox theme or plugin, but I don't know is it possible or not.

**Comment by dongle-the-gadget** [comment]
You'd need to make Firefox use the native Windows title bar for MFE to work with it, while yes we could provide a DLL hook for that, DLL hooks in general are very complicated and can break very easily.

**Comment by Void48** [comment]
understood. well hopefully someone will wanna give it a shot and experiment :D

**Comment by dongle-the-gadget** [comment]
@Void48 update: It's now possible via CSS:
https://www.reddit.com/r/FirefoxCSS/comments/tpkz9v/windows_11_mica_acrylic_for_firefox/
https://github.com/QNetITQ/WaveFox

**Comment by moonlumen** [comment]
> @Void48 update: It's now possible via CSS: https://www.reddit.com/r/FirefoxCSS/comments/tpkz9v/windows_11_mica_acrylic_for_firefox/ https://github.com/QNetITQ/WaveFox

this stopped working, any new methods?

**Comment by dongle-the-gadget** [comment]
Unfortunately, your only option is to use an older version of Firefox (95 ESR last I remember). Mozilla completely removed the Windows 7 glass code, which causes CSS themes using it to break.
________________________________

**Comment by Skyyblaze** [comment]
The latest Firefox 115 ESR release still has the required code so users can use that for a while and still get security patches until hopefully a new way is found.
