### ISSUE TITLE
Crash after sleep

### ISSUE THREAD

**Issue by provalinf** [minusium/MicaForEveryone#12]
Hi,
After resume, MicaFE crash.
I did not clearly identify if it is to the resume or to the connection of an external monitor, these two elements were together when I had this error anyway.
<img width="425" alt="image" src="https://user-images.githubusercontent.com/15704455/148352383-7ae8c4f0-5ff8-4241-958b-81bb3799572b.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/15704455/148352442-2236110b-b80f-41b9-b4f2-9db24cb3b7c8.png">

**Comment by minusium** [comment]
Thanks for your report
I've seen this error too and it can be fixed easily but I didn't try to do it but I'll fix it soon.

**Comment by minusium** [comment]
new version with fix released
