### ISSUE TITLE
Light mode is broken (White text)

### ISSUE THREAD

**Issue by NiZi9** [minusium/MicaForEveryone#14]
When using the light theme, most text is also white. Is this a known issue? Is it fixable?
See: https://imgur.com/a/7h18Cvi

**Comment by minusium** [comment]
Did you enable Extend Frame Into Client Area?

**Comment by NiZi9** [comment]
Yes

**Comment by minusium** [comment]
That's the reason, extend frame into client area doesn't work well on all apps and it's not recommended to enable it. I had this documented but seems like I removed it some how I should add it again.

**Comment by efsfssf** [comment]
![image](https://user-images.githubusercontent.com/29039987/149009194-e1a3168a-9547-492f-a076-a3cdf0e226fb.png)
Confirm. The background does not apply any effect, and the text becomes unreadable. Almost everywhere.
