### ISSUE TITLE
Run at Startup 

### ISSUE THREAD

**Issue by totallygeekdom** [minusium/MicaForEveryone#15]
I put a shortcut of the application in the startup folder. The app gives an error when the shortcut is used. Is there a way to have the app run at startup without putting the whole app in the folder?

**Comment by Void48** [comment]
This would be nice

**Comment by minusium** [comment]
I had this planned but still I didn't do that. You can create a shortcut of main executable then put that shortcut to Startup folder, I did that myself and it works.

**Comment by totallygeekdom** [comment]
> I had this planned but still I didn't do that. You can create a shortcut of main executable then put that shortcut to Startup folder, I did that myself and it works.

that's what I did but it didn't work

**Comment by minusium** [comment]
> that's what I did but it didn't work

weird, it's working for me.
![image](https://user-images.githubusercontent.com/21140798/149927114-2a93c23e-cd20-4794-ac88-a66bd391d4a6.png)
![image](https://user-images.githubusercontent.com/21140798/149927268-9b5be888-07fe-43bd-9825-6469b939b0f4.png)

**Comment by Void48** [comment]
😕Not working for me. will there be an option to enable from tray icon? 

> > that's what I did but it didn't work
> 
> weird, it's working for me. ![image](https://user-images.githubusercontent.com/21140798/149927114-2a93c23e-cd20-4794-ac88-a66bd391d4a6.png) ![image](https://user-images.githubusercontent.com/21140798/149927268-9b5be888-07fe-43bd-9825-6469b939b0f4.png)

**Comment by minusium** [comment]
> 😕Not working for me. will there be an option to enable from tray icon?

sure, planned for next release.

**Comment by CryoManne** [comment]
It doesn't work even if run app manually right after startup. So I found a workaround. Create a task to run MicaForEveryone in Task Scheduler and set 30 sec delay. Now it works (but not appears in Startup tab)
