### ISSUE TITLE
App Fails to run

### ISSUE THREAD

**Issue by ThePhantomOfTheOpera69** [minusium/MicaForEveryone#17]
Attempting to open the MicaForEveryone.exe file does nothing lol. I am running Windows 11 Build 22543.1000 and it just breaks even after installing the .net crap, restarting and running as admin. PLEASE FIX

**Comment by minusium** [comment]
It should work fine if you have .net core 3.1 runtime

**Comment by Void48** [comment]
> It should work fine if you have .net core 3.1 runtime

I had to get the SDK

**Comment by minusium** [comment]
> I had to get the SDK
just runtime is fine, even desktop runtime is not required as I don't use winforms and wpf

**Comment by Void48** [comment]
> > I had to get the SDK
> 
> just runtime is fine, even desktop runtime is not required as I don't use winforms and wpf

well it wasn't enough for me so idk. It wouldnt work without the SDK

**Comment by minusium** [comment]
I close this because no response from author
