### ISSUE TITLE
App fails to run (10.0.22543)

### ISSUE THREAD

**Issue by bhaiest** [minusium/MicaForEveryone#19]
App doesn't launch with the error about missing .NET Core, however both the SDK, Core and NETDesktop runtimes are installed.
![image](https://user-images.githubusercontent.com/97450182/151701055-a6b4bbbf-fa02-4cf6-bc52-8e0f4f7b8bbe.png)

**Comment by minusium** [comment]
You need .net core runtime 3.1, you have this version?

**Comment by bhaiest** [comment]
> You need .net core runtime 3.1, you have this version?

![image](https://user-images.githubusercontent.com/97450182/151707137-c7a7c2dc-0bc5-4b8f-a90a-17b922f5eff3.png)
indeed, i do.

**Comment by bhaiest** [comment]
UPD: Installed the x86 core, still didn't work

**Comment by bhaiest** [comment]
Description
Faulting Application Path:	C:\Users\vak\Downloads\mfe-v0.0.4.0-x64\MicaForEveryone.exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	5GVGKRK4OUUSSDURVVWEU55ILHL4CUFW
Problem Signature 02:	0.0.4.0
Problem Signature 03:	61731974
Problem Signature 04:	MicaForEveryone.UI
Problem Signature 05:	0.0.4.0
Problem Signature 06:	61cd6b28
Problem Signature 07:	1
Problem Signature 08:	6
Problem Signature 09:	System.IO.FileNotFoundException
OS Version:	10.0.22543.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	b46e
Additional Information 2:	b46eabfde862871735118db2cfe69274
Additional Information 3:	4e35
Additional Information 4:	4e357be6b27cb16cc5e331848a9fb65c

**Comment by minusium** [comment]
> System.IO.FileNotFoundException

Oh I think it's my fault, maybe it can't find config file, try downloading MicaForEveryone.conf from repo and put it in the same folder as app.
Maybe same issue as #17

**Comment by bhaiest** [comment]
> > System.IO.FileNotFoundException
> 
> Oh I think it's my fault, maybe it can't find config file, try downloading MicaForEveryone.conf from repo and put it in the same folder as app. Maybe same issue as #17

![image](https://user-images.githubusercontent.com/97450182/151708402-4ac61c0b-64aa-400a-bbb3-5012908bbe32.png)
Nope, didn't help.

**Comment by bhaiest** [comment]
Description
Faulting Application Path:	C:\Users\vak\Downloads\mfe-v0.0.4.1-x64\MicaForEveryone.UI.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	MicaForEveryone.UI.exe
Application Version:	0.0.4.1
Application Timestamp:	61d6b45f
Fault Module Name:	KERNELBASE.dll
Fault Module Version:	10.0.22543.1000
Fault Module Timestamp:	79a69917
Exception Code:	e0434352
Exception Offset:	000000000001228c
OS Version:	10.0.22543.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	f496
Additional Information 2:	f49666310f11c732250f3d103189092b
Additional Information 3:	525a
Additional Information 4:	525aace9975a723d96939c195b887336

**Comment by bhaiest** [comment]
Do i need to downgrade to 22000.* or so?

**Comment by minusium** [comment]
> Do i need to downgrade to 22000.* or so?

No it should work on any build

> Description
Faulting Application Path: C:\Users\vak\Downloads\mfe-v0.0.4.1-x64\MicaForEveryone.UI.exe

That's not main executable it's expected to crash

> Nope, didn't help.

You got .net core error, that means you don't have .net core 3.1
If you have then idk why you get this error, try building it yourself.

**Comment by bhaiest** [comment]
![image](https://user-images.githubusercontent.com/97450182/151715315-a6b748ba-6450-4613-85f4-4f4bcdb05932.png)
I compiled from source, with ALL possible dependencies related to .NET Core installed now

```
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[10764] MicaForEveryone.exe' has exited with code 2147516566 (0x80008096).
```
Still does not run, any possible fix here?

**Comment by bhaiest** [comment]
![image](https://user-images.githubusercontent.com/97450182/151715449-0fd0bd01-0b7b-49bb-9a07-2867c16d65e7.png)
List of all runtimes
and SDKs:
![image](https://user-images.githubusercontent.com/97450182/151715463-dee14071-7228-46e1-b2de-68a90378e0f7.png)

**Comment by rounk-ctrl** [comment]
You need .net 6.0 Desktop Runtime not the SDK

**Comment by minusium** [comment]
@behaiest @ThePhantomOfTheOpera69
Go to Mica For Everyone's folder and open command prompt/powershell/terminal and run this:
`dotnet .\MicaForEveryone.dll`
What happens?

**Comment by adislice** [comment]
I have same issue on Insider Dev build 22543.1000

```
Description:
Application: MicaForEveryone.exe
CoreCLR Version: 4.700.21.56803
.NET Core Version: 3.1.22
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: The specified module could not be found. (0x8007007E)
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication..ctor()
   at MicaForEveryone.UI.App..ctor() in D:\projects\MicaForEveryone\MicaForEveryone.UI\App.xaml.cs:line 7
   at MicaForEveryone.App..ctor() in D:\projects\MicaForEveryone\MicaForEveryone\App.cs:line 9
   at MicaForEveryone.Program.Main(String[] args) in D:\projects\MicaForEveryone\MicaForEveryone\Program.cs:line 16
```
Installed runtimes: 
![image](https://user-images.githubusercontent.com/29942831/152200080-341a0735-702e-4694-bed8-0a3a996c52c1.png)

**Comment by minusium** [comment]
Open MicaForEveryone.runtimeconfig.json with notepad and replace its content with this, check if it works or not.
```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.WindowsDesktop.App",
      "version": "3.1.0"
    }
  }
}
```

**Comment by adislice** [comment]
> Open MicaForEveryone.runtimeconfig.json with notepad and replace its content with this, check if it works or not.
> 
> ```
> {
>   "runtimeOptions": {
>     "tfm": "netcoreapp3.1",
>     "framework": {
>       "name": "Microsoft.WindowsDesktop.App",
>       "version": "3.1.0"
>     }
>   }
> }
> ```

Still does not work
```
Application: MicaForEveryone.exe
CoreCLR Version: 4.700.21.56803
.NET Core Version: 3.1.22
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: The specified module could not be found. (0x8007007E)
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication..ctor()
   at MicaForEveryone.UI.App..ctor() in D:\projects\MicaForEveryone\MicaForEveryone.UI\App.xaml.cs:line 7
   at MicaForEveryone.App..ctor() in D:\projects\MicaForEveryone\MicaForEveryone\App.cs:line 9
   at MicaForEveryone.Program.Main(String[] args) in D:\projects\MicaForEveryone\MicaForEveryone\Program.cs:line 16

```

![MicaForEveryone runtimeconfig json - Notepad_b1](https://user-images.githubusercontent.com/29942831/152205966-134c84a3-bf95-4462-b76d-165fcf9d4d40.png)

**Comment by adislice** [comment]
It works after installing MS Visual C++ 2015-2022 Redistributable 👍
![Screenshot 2022-02-03 004247](https://user-images.githubusercontent.com/29942831/152208147-ea6e401a-3de7-4e5c-971c-99b3f96e4cf5.png)

**Comment by rounk-ctrl** [comment]
yes MS Visual C++ 2015-2022 is needed because XAML islands
![image](https://user-images.githubusercontent.com/70931017/152671555-28fe4585-2162-4e04-b855-a069bd4d26ca.png)

**Comment by minusium** [comment]
I see that's why we use VCRTForwarders, I just forgot that because I assumed everyone would have that. I even don't remember when I installed it.

**Comment by minusium** [comment]
I close this because no response from author.
