### ISSUE TITLE
Mica (and other) does not work

### ISSUE THREAD

**Issue by efsfssf** [minusium/MicaForEveryone#2]
Windows 11 build 22523. Interface language: Russian (I don't know how in other languages)
![image](https://user-images.githubusercontent.com/29039987/146652162-6976a6ab-ae30-49ed-bc07-9d3932dcf9b9.png)

**Comment by minusium** [comment]
It's ok if you don't use ExtendFrameIntoClientArea. It doesn't look good on all apps and it's not my fault, but I added a config file and you can use it to set config for each app.
