### ISSUE TITLE
Mica effect being applied to ShareX screenrecordings? 

### ISSUE THREAD

**Issue by Void48** [minusium/MicaForEveryone#20]
![image](https://user-images.githubusercontent.com/85196642/151984547-3b1e235f-dd62-4888-b270-16520eb478d5.png)
when I start screen recording it applies the mica effect to the region

**Comment by minusium** [comment]
Yes, it happened to me too. You just have to add a rule to config file to disable Mica effect on ShareX, like this:
```
Process: "ShareX" {
    TitleBarColor = Default
    BackdropPreference = Default
    ExtendFrameIntoClientArea = False
}
```
