### ISSUE TITLE
PowerToys mica titlebar doesn't work anymore?

### ISSUE THREAD

**Issue by Void48** [minusium/MicaForEveryone#21]
I used to have mica titlebar on powertoys but now it wont apply itself

**Comment by minusium** [comment]
You're using latest release or master branch?

**Comment by Void48** [comment]
> You're using latest release or master branch?

latest release. is there gonna be a new release soon? or would setting up gh actions work for nightly releases?

**Comment by minusium** [comment]
Well nothing's changed on release so idk, maybe tell me about anything you did, related to Mica For Everyone, or maybe you just restarted PowerToys as admin so Mica For Everyone doesn't have access to it.

> is there gonna be a new release soon?

Maybe, Settings GUI is nearly done. There are something else I should add too.

> would setting up gh actions work for nightly releases?

I'll try that

**Comment by Void48** [comment]
oh auto updater would actually be amazing if thats possible

**Comment by Void48** [comment]
also I don't use powertoys as admin. my win11 version is: 22543.1000

**Comment by fbtwitter** [comment]
try to run micaforeveryone.exe as admin.
it works for me.

**Comment by Void48** [comment]
> try to run micaforeveryone.exe as admin. it works for me.

running as admin fixed it. @minusium could you add run as admin on startup option?
