### ISSUE TITLE
Does not work with new Windows 11 beta SDK

### ISSUE THREAD

**Issue by jt-github** [minusium/MicaForEveryone#22]
This is less of a real issue and more informational in case it hasn't been tried before.  I wouldn't expect your project to actually function with the beta SDK unless it was specifically designed to do so.

Just for fun, I removed the Windows 11 SDK (10.0.22000.0) and installed the Windows 11 beta (10.0.22543.0) SDK my PC running Windows 11 Insider (dev channel, build 10.0.22543.0).  I attempted to build (after I updated the MicaForEveryone.UI project to point to the newer SDK) which resulted in the following errors:

```
Error: 'C:\Program Files (x86)\Windows Kits\10\\Platforms\UAP\10.0.22543.0\PreviousPlatforms.xml' does not contain an entry for platform version '10.0.22000.0'. Is your Target Platform Min Version a suported SDK? MicaForEveryone.UI\App.xaml		
Error: 'C:\Program Files (x86)\Windows Kits\10\\Platforms\UAP\10.0.22543.0\PreviousPlatforms.xml' does not contain an entry for platform version '10.0.22000.0'. Is your Target Platform Min Version a suported SDK?	MicaForEveryone.UI\ContentDialogView.xaml		
Error: 'C:\Program Files (x86)\Windows Kits\10\\Platforms\UAP\10.0.22543.0\PreviousPlatforms.xml' does not contain an entry for platform version '10.0.22000.0'. Is your Target Platform Min Version a suported SDK?	MicaForEveryone.UI\SettingsView.xaml		
Error: 'C:\Program Files (x86)\Windows Kits\10\\Platforms\UAP\10.0.22543.0\PreviousPlatforms.xml' does not contain an entry for platform version '10.0.22000.0'. Is your Target Platform Min Version a suported SDK?	MicaForEveryone.UI\TrayIconView.xaml		
Warning: The referenced component '....nuget\packages\microsoft.toolkit.win32.ui.xamlapplication\6.1.3\build\..\lib\uap10.0\Microsoft.Toolkit.Win32.UI.XamlHost.winmd' could not be found.	MicaForEveryone.UI
```

**Comment by minusium** [comment]
I don't know, but try to clean, remove bin and obj folder from MicaForEveryone and MicaForEveryone.UI folders, restore nuget packages again and rebuild project. Seems like you didn't rebuild project properly. MicaForEveryone and MicaForEveryone.UI project both contain Windows SDK version, change it in both. It should work.

**Comment by jt-github** [comment]
Well, I tried all that and even upgraded Microsoft.UI.XAML from 2.7.1 to 2.8.0 (both are prereleases) with no luck.  It still gave the same errors, so there is some dependency I cannot find that keeps calling on v22000 (so it's probably still my fault).

So, I took UI.XAML back to 2.7.1, then "cheated" and added 22000 (stolen from the 22000 version of the file) to the PreviousPlatforms.xml file in 22543.  Cleaned and rebuilt and that worked... but I assume it's using a fallback version, which is essentially the same as just using the 22000 version of the SDK.

Now if only someone could create an app to totally override things like Acrylic so we could turn it on full-time for all windows so that we get proper transparency all the way from top to bottom because if Windows Vista PCs could (sometimes) handle it, our much more current hardware can handle it with ease, even if we're wasting some power...  But that's not your problem!

**Comment by jt-github** [comment]
Extending Frame Into Client Area works so nicely with Explorer when it's the currently active app (it's nice to see almost fully implemented Acrylic transparency) but it's such a bummer that it turns into ugly grayness when the app window is no longer in focus.  Again, that's not something I think you have any way to control, but maybe someday...

**Comment by minusium** [comment]
You should checkout Mica CMD

**Comment by jt-github** [comment]
Link?  (I tried a cursory search and came up empty.)

**Comment by minusium** [comment]
Just open CMD when MFE is running, You'll like it.

**Comment by minusium** [comment]
Close this if your problem is solved. I won't upgrade SDK version until new build goes to beta channel.

**Comment by jt-github** [comment]
Ah, the old school command prompt.  Yes, it looks great with the MFE effect!  

Have you tried Microsoft's Windows Terminal?  It's a fantastic console program with way more goodies than CMD and it supports built-in (and configurable) acrylic, although using MFE to make the title bar acrylic is the icing on the cake.  You can get Windows Terminal on the Microsoft Store.

Finally, understood on the beta.  Closing!

**Comment by minusium** [comment]
Yes I see. It can't work on Terminal because it doesn't use system titlebar.
