### ISSUE TITLE
Newly opened windows do not inherit style change

### ISSUE THREAD

**Issue by jt-github** [minusium/MicaForEveryone#23]
When opening a new window of an app specified to be "enhanced" with MFE, it does not automatically acquire the updated style (an Acrylic title bar background, for example); it retains the Windows default style.

Restarting MFE or just reloading the config file does update the style on any already-open windows.

**Comment by jt-github** [comment]
On a less important note, when a window is not maximized it shows the Extend Frame Into Client Area effect only until it is maximized, which then redraws the original style (and the larger-scale translucency does not return if the window is restored to its original size).  Reloading the app or just reloading the config file is the only way to re-apply the effect.

**Comment by minusium** [comment]
latest release or latest commit?

**Comment by jt-github** [comment]
0.0.4.1, which I grabbed from master maybe an hour before I posted this issue.

**Comment by jt-github** [comment]
Thanks for the quick fix!
