### ISSUE TITLE
Cannot add rule via the Settings app

### ISSUE THREAD

**Issue by jt-github** [minusium/MicaForEveryone#25]
In the MFE Settings app, clicking on Add Rule provides the two expected options, but the app crashes when you click on either of them.  See attached image.

![Mica For Everyone Add Rule Unhandled Exception](https://user-images.githubusercontent.com/1504620/152211978-dda42992-b387-4559-9c9e-8909e85df8e0.png)

**Comment by jt-github** [comment]
You can, of course, add rules by manually editing the config file.

**Comment by minusium** [comment]
It's not implemented, yet. I'm working on it.

**Comment by jt-github** [comment]
Well that would explain it then. :)
