### ISSUE TITLE
Saving a rule bounces back to General tab

### ISSUE THREAD

**Issue by jt-github** [minusium/MicaForEveryone#26]
Saving any rule in the MFE Settings app causes the focus to return to the General tab.  It should instead stay focused on the currently visible tab (and just disable the Save button).

**Comment by minusium** [comment]
I know, but I can't do that. It returns to General tab because it reloads config file.

**Comment by jt-github** [comment]
Ah, makes sense, but I suspect it wouldn't be too hard to store the current tab in a variable (each time you change tabs) and then, upon loading the config, attempt to return to that stored tab if it still exists.

**Comment by minusium** [comment]
That would be nice, You're right this is possible. I didn't try to save it because it may doesn't exist, but I can check if it exists then return to that tab.

**Comment by jt-github** [comment]
Awesome.  Works well!  

One behavior I'm observing in the current version that could be seen as either distracting or a good way to remind users that they need to Save to apply changes:
Switch from the General tab to any other tab and the Save button will very briefly appear as enabled and then switch to the disabled state.

**Comment by minusium** [comment]
Well I don't handle enabling and disabling save button, I let xaml binding do that for me.
