### ISSUE TITLE
Trying to open settings gives error and crashes MFE?

### ISSUE THREAD

**Issue by Void48** [minusium/MicaForEveryone#29]
![image](https://user-images.githubusercontent.com/85196642/152716068-f4e04e89-64c5-425f-91da-32d53579a90f.png)
![image](https://user-images.githubusercontent.com/85196642/152716078-27c6d1d4-6f3f-45ac-a94e-589870f4d14b.png)

**Comment by dongle-the-gadget** [comment]
I managed to workaround this issue in a PR and apparently @minusium reverted it, haha

**Comment by minusium** [comment]
I added uint to `enum DWM_SYSTEMBACKDROP_TYPE : uint` and it did not throw that error so I thought that works too, but appearntly it didn't👀 Idk why this doesn't happen on my machine but I'll add again the workaround.

**Comment by dongle-the-gadget** [comment]
> I just realized I'm on build 22000 and DWM_SYSTEMBACKDROP_TYPE is used on build 22523 so there's no way that I would get this error.

(haha, and also facepalm)

**Comment by minusium** [comment]
> Can't you just use Debug?

On debug still it doesn't use that method, but I can make it use. Nevermind we already know the fix it's not a big deal.

**Comment by dongle-the-gadget** [comment]
Well of course it isn't going to apply any changes but at least we can test if the code runs.
