### ISSUE TITLE
Can you add more effects like Acrylic?

### ISSUE THREAD

**Issue by LukieEdward** [minusium/MicaForEveryone#31]
Maybe with acrylic it would look more like what Windows 7 had

**Comment by Void48** [comment]
> Maybe with acrylic it would look more like what Windows 7 had

Acrylic effect is already supported

**Comment by dongle-the-gadget** [comment]
> Maybe with acrylic it would look more like what Windows 7 had

As Void48 said, Acrylic is already supported for people with 22523 or newer.
