### ISSUE TITLE
[Suggestion] Open config file location button

### ISSUE THREAD

**Issue by Void48** [minusium/MicaForEveryone#33]

**Comment by dongle-the-gadget** [comment]
@Void48 I believe **Open in default text editor** should usually do the job?

**Comment by Void48** [comment]
> @Void48 I believe **Open in default text editor** should usually do the job?

That just opens the config file. At least there should be text saying that its located in %localappdata%

**Comment by dongle-the-gadget** [comment]
> > @Void48 I believe **Open in default text editor** should usually do the job?
> 
> That just opens the config file. At least there should be text saying that its located in %localappdata%

I believe that's kind of unnecessary, considering how many text editors reveal the path.
(Except the new Notepad, but you can figure that out using Save as)

**Comment by minusium** [comment]
I'll add an option to customize config file path in settings.

**Comment by dongle-the-gadget** [comment]
@minusium I believe you should just force the Windows provisioned path for MSIX.

**Comment by minusium** [comment]
> I believe you should just force the Windows provisioned path for MSIX.

I have to do that too.

**Comment by dongle-the-gadget** [comment]
> > I believe you should just force the Windows provisioned path for MSIX.
> 
> I have to do that too.

Well it isn't difficult to check if the app is in MSIX, at all. In fact there's a NuGet for that (DesktopBridge.Helpers)

**Comment by minusium** [comment]
> Well it isn't difficult to check if the app is in MSIX, at all. In fact there's a NuGet for that (DesktopBridge.Helpers)

I already do that to figure out I should use Win32StartupService or UwpStartupService, it just a call to GetCurrentPackageFullName if it fails then it means app is not packaged.
