### ISSUE TITLE
ContentDialog crashes on Light Mode

### ISSUE THREAD

**Issue by dongle-the-gadget** [minusium/MicaForEveryone#37]
Trying to create a new rule in the Settings window causes the program to crash completely in 0.1.0.0 Alpha 3 (MSIX, clean install).

**Comment by dongle-the-gadget** [comment]
> I can't reproduce it.

oh

**Comment by dongle-the-gadget** [comment]
Looks like this is the problem
<img width="668" alt="image" src="https://user-images.githubusercontent.com/29563098/153545590-c9657dd4-c3e8-452c-9433-b1fa4c499a1d.png">

**Comment by dongle-the-gadget** [comment]
So turns out the Alpha value of the foreground got way out of wack for whatever reason. Added some code that changes the foreground Alpha value to 0 and it didn't throw anything.

**Comment by minusium** [comment]
How did you managed to attach debugger to MSIX package?
This exception is related to Content Dialog, not Config File. Could you check if value of `color.A` is 255?

**Comment by dongle-the-gadget** [comment]
> How did you managed to attach debugger to MSIX package? This exception is related to Content Dialog, not Config File. Could you check if value of `color.A` is 255?

I actually used Win32 instead haha, not packaged.

**Comment by dongle-the-gadget** [comment]
However it doesn't look like this behavior differs much between packaged and unpackaged

**Comment by minusium** [comment]
> So turns out the Alpha value of the foreground got way out of wack for whatever reason. Added some code that changes the foreground Alpha value to 0 and it didn't throw anything.

Yes when color has alpha this happens. Idk why `color.A` is something else while I explicitly set it to 0.

**Comment by dongle-the-gadget** [comment]
> > So turns out the Alpha value of the foreground got way out of wack for whatever reason. Added some code that changes the foreground Alpha value to 0 and it didn't throw anything.
> 
> Yes when color has alpha this happens. Idk why `color.A` is something else while I explicitly set it to 0.

It's actually for text color, caption background doesn't have this bug.

**Comment by dongle-the-gadget** [comment]
Also now I tried to repro the bug, it didn't happen. Maybe it's a bug on Light Mode?

**Comment by dongle-the-gadget** [comment]
Yeah on Light Mode the caption text color is now #E4000000, which if translated to `COLORREF` means A = 27, R = 0, G = 0, B = 0.

**Comment by dongle-the-gadget** [comment]
So turns out this is an error related to invalid color values on Light Mode. Dark mode isn't affected.

**Comment by minusium** [comment]
> Also now I tried to repro the bug, it didn't happen. Maybe it's a bug on Light Mode?

Maybe, I'll just set alpha of foreground color to 0, too. Thanks for report.

**Comment by dongle-the-gadget** [comment]
It's kind of peculiar that this bug only affects Light Mode.
