### ISSUE TITLE
Font turned white on white windows

### ISSUE THREAD

**Issue by st503max** [minusium/MicaForEveryone#39]
Program: [Internet Download Manager](https://www.internetdownloadmanager.com/)
Issue: Font turned white on white windows
I have tried to set everything to Default, end and delete the application, but it has no effect.
![IDM](https://user-images.githubusercontent.com/41504877/153713171-ac76eca1-e298-4281-ab66-e5063ebc4540.png)

**Comment by st503max** [comment]
Thanks for your reply!

I used to enable ExtendFrameToClientArea but not now.
This is the current value of MicaForEveryone.conf
```
   TitleBarColor = Default
   BackdropPreference = Default
   ExtendFrameToClientArea = false
```

I don't know if EnableBlurBehind is referring to [this](https://www.tenforums.com/tutorials/5763-turn-off-blur-start-menu-taskbar-windows-10-a.html).
If so, I don't have this value in registry.


I would like to know if there is a way to revert to the state before MicaForEveryone was used. 
Maybe I made a mistake somewhere, please help me.

**Comment by minusium** [comment]
Just exit from IDM and open it again. If IDM doesn't work well with MFE you can add a rule to for it so it'll ignore IDM.
EnableBlurBehind makes windows transparent. I'll add document and screenshot for it.

**Comment by minusium** [comment]
I close this issue as no response received from author
