### ISSUE TITLE
[basic question] How to install?

### ISSUE THREAD

**Issue by ianyepan** [minusium/MicaForEveryone#45]
I downloaded and extracted the zip folder, ran the EXE file and it works fine. But how do I correctly install it? Do I literally just copy the file over to a new folder under Program Files? Should I keep all the other DDL, JSON, PRI files that are in the zip folder alongside?

**Comment by dongle-the-gadget** [comment]
The ZIP folder contains all the files you need to run Mica For Everyone. Just execute `MicaForEveryone.exe` and it will run, and yeah it's a good idea to keep all the files.

**Comment by ianyepan** [comment]
Thanks!
