### ISSUE TITLE
Nothing happens upon opening MicaForEveryone.exe

### ISSUE THREAD

**Issue by Mine-Modder** [minusium/MicaForEveryone#47]
Attempting to run release v0.0.4.1 by double clicking either MicaForEveryone.exe or MicaForEveryone.UI.exe does not seem to do anything. No app appears, not in the taskbar and not in the system tray. Double clicking MicaForEveryone.exe makes it appear in task manager for a short moment, before automatically closing. Only the first time it prompted to install Windows Desktop Runtime.

Running an old version (v2) seems to work fine, but obviously misses a lot of features added in the newer releases. May be related to issue #5.

The virtual machine is running Windows 11 Insider Dev Build 22557.1.

**Comment by minusium** [comment]
Try installing [Visual C++ Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=48145) and [.NET Core Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/3.1).

**Comment by Mine-Modder** [comment]
Tried installing both, but MicaForEveryone still doesn't open. Are there any logs to include that might be useful to debug this?

**Comment by Mine-Modder** [comment]
MicaForEveryone still doesn't work on the VM after installing both of these.

The following errors appear in Event Viewer:

.NET Runtime
```
Application: MicaForEveryone.exe
CoreCLR Version: 4.700.21.56803
.NET Core Version: 3.1.22
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: The specified module could not be found. (0x8007007E)
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication..ctor()
   at MicaForEveryone.UI.App..ctor() in D:\projects\MicaForEveryone\MicaForEveryone.UI\App.xaml.cs:line 7
   at MicaForEveryone.App..ctor() in D:\projects\MicaForEveryone\MicaForEveryone\App.cs:line 9
   at MicaForEveryone.Program.Main(String[] args) in D:\projects\MicaForEveryone\MicaForEveryone\Program.cs:line 16
```

Application Error
```
Faulting application name: MicaForEveryone.exe, version: 0.0.4.1, time stamp: 0x619ae151
Faulting module name: KERNELBASE.dll, version: 10.0.22557.1, time stamp: 0x509683d6
Exception code: 0xe0434352
Fault offset: 0x000000000001358c
Faulting process ID: 0x0x4BC
Faulting application start time: 0x0x1D82835F5293349
Faulting application path: C:\Users\<User>\Downloads\mfe-v0.0.4.1-x64\MicaForEveryone.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: fdf85bf3-0296-4d55-b4a1-d7833a95f59d
Faulting package full name: 
Faulting package-relative application ID: 
```

(`<User>` is Windows username}

Windows Error Reporting
```
Fault bucket 1842511972058849262, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: UC2ELS4RLHOHLA5GSE4GBYNXFFVXIJD1
P2: 0.0.4.1
P3: 619ae151
P4: MicaForEveryone.UI
P5: 0.0.4.1
P6: 61d6b45f
P7: 1
P8: 6
P9: System.IO.FileNotFoundException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ea2c1886-79f1-4ae2-8be2-c2cb48cfb103.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f9ce96fa-99d1-42f5-84bc-27598257f516.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20220219_1 EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f7565ec8-e217-46f3-bd77-25b6f33cf65c.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d4e20067-ccaf-4b1c-80ad-0218e6d11937.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1c48e7f5-9d0f-48aa-971e-8097479bb46f.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5eb5a23d-9489-4b14-8173-e4be81e409b6.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.daf951e8-616f-4e62-b18e-cd4fd56124c2.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_UC2ELS4RLHOHLA5G_2a6292828b1e20f17d3baaff596bd9fb31125979_4e6189ae_7a7e69ba-7b6e-46bb-88e9-455d70c16f0a

Analysis symbol: 
Rechecking for solution: 0
Report Id: fdf85bf3-0296-4d55-b4a1-d7833a95f59d
Report Status: 2147487744
Hashed bucket: 57c347dd33e8b6f85991eae064f8dfee
Cab Guid: 0
```

**Comment by minusium** [comment]
I don't know what's wrong, but I could understand that a file that's required by Xaml Islands can't be found. Xaml Islands require Visual C++ Runtime so make sure if you have it installed.
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by manymanecki** [comment]
I have got the same problem and almost the exact same errors in the event viewers as above. I have installed all the required redistributables and even some additional ones, such as older Visual Studios, but to no avail. Fresh Windows 11 install with the newest update. I can provide event viewer error but they are almost the same as Mine-Modder's.

**Comment by Mine-Modder** [comment]
Copying the `runtimes\win10-x64\native` to `runtimes\win` seems to have fixed the issue.

**Comment by minusium** [comment]
> Copying the contents of the runtimes\win10-x64\native folder to runtimes\win\native seems to have fixed the issue.

Weird. I can't help as I can't reproduce it, but those files are copied by compiler not me.
