### ISSUE TITLE
Version 0.0.3 won't launch

### ISSUE THREAD

**Issue by KibSquib48** [minusium/MicaForEveryone#5]
**Windows version info:**
Edition	Windows 11 Home
Version	21H2
Installed on	‎Oct ‎2, ‎2021
OS build	22000.376
Experience	Windows Feature Experience Pack 1000.22000.376.0

When I double click MicaForEveryone.exe in the folder extracted from the .zip, nothing happens. 0.0.2 works and Reliability Monitor shows nothing. Running as admin also did not work.

**Comment by Void48** [comment]
Same issue

**Comment by KibSquib48** [comment]
update: just installed .NET Core 3.1 Runtime, still won't launch, but reliability monitor says this now

```
Source
MicaForEveryone.UWP

Summary
Stopped working

Date
‎Dec ‎23, ‎2021 2:46 PM

Status
Report sent

Description
Faulting Application Path:	C:\Users\kib47\Downloads\release-v0.0.3-x64\MicaForEveryone.UWP.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	MicaForEveryone.UWP.exe
Application Version:	0.0.3.0
Application Timestamp:	61c49a27
Fault Module Name:	KERNELBASE.dll
Fault Module Version:	10.0.22000.348
Fault Module Timestamp:	065c557a
Exception Code:	e0434352
Exception Offset:	000000000004478c
OS Version:	10.0.22000.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	f496
Additional Information 2:	f49666310f11c732250f3d103189092b
Additional Information 3:	73ad
Additional Information 4:	73ad8b980eadc20509e5600e347369bb

Extra information about the problem
Bucket ID:	a2aa56a3715746a8d9a9c8608afaeeea (1849229438986415850)
```

**Comment by dongle-the-gadget** [comment]
I ran a prerelease version of this and it worked fine, dunno what's causing this. Might need to debug latest source.

**Comment by dongle-the-gadget** [comment]
So I manually cloned the code and turns out that both Debug x64 and Release x64 works fine.

**Comment by dongle-the-gadget** [comment]
Can anyone try out [my build](https://github.com/minusium/MicaForEveryone/files/7771917/MicaForEveryone-0.0.3-Dongle-x64.zip) and see if it launches?

**Comment by dongle-the-gadget** [comment]
@KibSquib48 may I ask what runtime did you install? Desktop Runtime or just the Runtime?

**Comment by KibSquib48** [comment]
> @KibSquib48 may I ask what runtime did you install? Desktop Runtime or just the Runtime?

Apparently just Desktop Runtime, even though the website said the installer included both the Desktop Runtime and the Runtime

**Comment by KibSquib48** [comment]
> Can anyone try out [my build](https://github.com/minusium/MicaForEveryone/files/7771917/MicaForEveryone-0.0.3-Dongle-x64.zip) and see if it launches?
> 
> (note: it's for x64)

After installing the Runtime, the build of 0.0.3 in the releases page still doesn't work but this one does

**Comment by dongle-the-gadget** [comment]
Funny considering how both are basically the same code.

**Comment by minusium** [comment]
Thanks for reporting this, I realized that I'm missing some runtime-related libraries from release zip file and @dongle-the-gadget and I couldn't figure this out because we have the sdk installed on our PC. I updated zip files in release section so now it'll work, but you can keep using Dongle's build or copy "runtime" folder from his build to my build.
