### ISSUE TITLE
To run this application, you must install .NET Core. Always show startup

### ISSUE THREAD

**Issue by chuck00000** [minusium/MicaForEveryone#51]
![image](https://user-images.githubusercontent.com/98159699/159414898-fd95a5fa-7647-4a61-bc96-3f83227f8ec4.png)

Why startup always show this message? I already install this

**Comment by minusium** [comment]
Maybe you installed wrong version, Install .NET Core 3.1 version x64.

**Comment by chuck00000** [comment]
No, I didn't say clearly, I set this program "run on startup". when this computer startup, it's always show this message.

**Comment by minusium** [comment]
Oh so could run it, but it shows this message when running from startup task? That's weird. You're using msix version?

**Comment by chuck00000** [comment]
Yes, i install msix

**Comment by chuck00000** [comment]
Yes

**Comment by minusium** [comment]
MSIX version is self-contained it doesn't require .NET Core Runtime, now it's more weird.

**Comment by dongle-the-gadget** [comment]
I thought that we have set "SelfContained" to false?

**Comment by chuck00000** [comment]
I reinstall everything, problems solved. But why everytime I RESTART this application the settings value is restore default?

**Comment by minusium** [comment]
> I thought that we have set "SelfContained" to false?

It got removed again when we were trying to fix MSIX build error. Still I'm not sure if it's required or not, as output package has dependency on UWP .NET Core Package, I think only UWP apps using .NET Core Runtime can use that.

**Comment by minusium** [comment]
> But why everytime I RESTART this application the settings value is restore default?

Maybe sometimes it starts as unpackaged app, and sometimes starts as packaged app? Is it possible at all?

**Comment by chuck00000** [comment]
Restart my computer, all settings value is restore default

**Comment by minusium** [comment]
> Restart my computer, all settings value are restore default. I have to set again

What if you exit mfe (right click on tray icon and select exit) and then run it again?

**Comment by chuck00000** [comment]
It's also restore default

**Comment by minusium** [comment]
> It's also restore default

In Settings, General page, what is config file path?

**Comment by chuck00000** [comment]
C:\Users\username\AppData\Local\Packages\MicaForEveryone_hre44c6cb3hwj\LocalState\MicaForEveryone.conf

**Comment by chuck00000** [comment]
![image](https://user-images.githubusercontent.com/98159699/159600320-3b6c78f6-9198-4b05-84ba-6cf42b75fe98.png)

**Comment by chuck00000** [comment]
The config file didn't save anything

**Comment by chuck00000** [comment]
Just edit config file in notepad, problems solved
![image](https://user-images.githubusercontent.com/98159699/159633049-992991b7-aba6-4606-83e9-8dd3a81949ef.png)

Why File Explorer & mspaint  in app changes didn't reflect config file? I have to edit config file

**Comment by minusium** [comment]
> Why File Explorer & mspaint in app changes didn't reflect config file?

I couldn't understand what you're asking, but touching explorer and mspaint will mess with them so I added default rules to don't touch them. if your problem is solved now you can close this issue.

**Comment by chuck00000** [comment]
Er, change the file explorer & Mspaint  Transparent style effects in App, but config file didn't saved anything; exit App,run it again, the file explorer & Mspaint settings is restore default, I have set it again. But now I edit config file  file explorer & Mspaint value, So run this app again is also follow it rules.

**Comment by minusium** [comment]
You're right, I could reproduce it, it should be a bug in config file generator.
