### ISSUE TITLE
Windows lagging

### ISSUE THREAD

**Issue by PickycowXD** [minusium/MicaForEveryone#58]
All of my windows lag when I move them and its extremely disorienting, it starts when i start the app and doesn't stop until i reboot my machine.

**Comment by minusium** [comment]
First thing: MFE is not responsible for rendering backdrops so if you experience lags or bad rendering or anything similar it should be a bug in apps or the Windows itself.
Second thing: lags are expected when you use "Blur Behind" option. Disable it if you enabled it.
