### ISSUE TITLE
Acrylic/Blur-esque effect on Chrome pre-22523.

### ISSUE THREAD

**Issue by HeyItsJono** [minusium/MicaForEveryone#59]
This isn't so much reporting a bug that I want fixed, rather I'm reporting a bug which actually provides a feature I enjoy, and I'm wondering if there's any way to implement it as a more permanent option.

There is a way to apply an Acrylic/Blur like effect to Chrome's title bar on the latest release build of Windows 11 (21H2, 22000.593), when it would otherwise only be available on Insider Builds 22523 and later.
Unfortunately when the steps below to reproduce the bug are taken, it only applies to any currently open Chrome windows, any window opened after performing these steps will require you to re-do the steps to apply the blur.

1. Make a process rule for `chrome`
2. Set your `Titlebar Color` to "Light"
3. Set your `Extend Frame Into Client Area` to "Off"
4. Set your `Blur Behind` to "On"
5. Set your `Backdrop Type` to "None", then after selecting None, change your `Backdrop Type` to Mica.
6. All currently open Chrome windows should have the below look applied, which IMO is much nicer than Mica and I would appreciate a way of more consistently/permanently applying this effect if possible!

In case it matters, I'm running Windows 11 Enterprise (21H2, 22000.593), and MFE 1.0.6.1.
My Global Rules are `Titlebar Color` = System, `Backdrop Type` = Mica, `Extend Frame`  = Off, `Blur Behind` = Off.
I'd greatly appreciate any consideration you could give to making this a permanent option (if feasible), thanks!

Below is an image of the effect.
![YUv4ZUBB7Z](https://user-images.githubusercontent.com/4620093/161504508-3d4e3b29-5dfa-4013-8b40-4ce237a4b191.jpg)

**Comment by dongle-the-gadget** [comment]
Unfortunately, Blur Behind is a very experimental feature which is never intended to be used, like Extend Frame Into Client Area.

**Comment by dongle-the-gadget** [comment]
And I believe in this build it causes lag while trying to move and resize the window.

**Comment by HeyItsJono** [comment]
> Blur Behind is a very experimental feature which is never intended to be used, like Extend Frame Into Client Area.

I understand, I suppose it's interesting because Blur Behind alone doesn't cause this effect, you have to turn Mica on and off for it to appear, otherwise the titlebars just look like standard Light Mica. I was just wondering if since the Blur Behind option is there anyway and this effect is possible, it could be made available to end-users with the implication that it's an unsupported/experimental feature to be used at user's own risk.

> And I believe in this build it causes lag while trying to move and resize the window.

It doesn't seem to lag any more than without Blur Behind for me, and I'm not on an especially powerful laptop or anything.

**Comment by dongle-the-gadget** [comment]
I'm using 22581, and I could not replicate this effect, however testing on explorer confirms that Blur Behind does apply to new windows correctly. This looks like a problem with either your configuration or Chrome itself (I think it's more likely the latter as it only supports the DWM frame in Windows 7)

**Comment by dongle-the-gadget** [comment]
You can try disabling the custom Windows 10 title bar in Chrome by using `-disable-windows10-custom-titlebar` (81+) or `--disable-features=Windows10CustomTitlebar` (80-)

**Comment by dongle-the-gadget** [comment]
Blur Behind is kind of borked on my install
<img width="894" alt="image" src="https://user-images.githubusercontent.com/29563098/161511093-2bc02222-6c64-4cde-b22c-2c773b361f14.png">
Notice how the menu bar and title bar in Paint doesn't have translucency while the status bar does.

**Comment by HeyItsJono** [comment]
> You can try disabling the custom Windows 10 title bar in Chrome by using `-disable-windows10-custom-titlebar` (81+) or `--disable-features=Windows10CustomTitlebar` (80-)

Sorry I forgot to mention the really relevant fact that I already had the --disable-windows10-custom-titlebar flag enabled so yeah it is required to re-create this effect.



> Blur Behind is kind of borked on my install <img alt="image" width="894" src="https://user-images.githubusercontent.com/29563098/161511093-2bc02222-6c64-4cde-b22c-2c773b361f14.png"> Notice how the menu bar and title bar in Paint doesn't have translucency while the status bar does.

I agree Blur Behind in general is pretty messy with some other applications, I get the same results with Paint.

**Comment by dongle-the-gadget** [comment]
Blur Behind applies completely fine to new windows for me, mind to share your config file?

**Comment by HeyItsJono** [comment]
> Blur Behind applies completely fine to new windows for me, mind to share your config file?

```
# Mica For Everyone Configuration

Global {
  TitleBarColor             = System  # available modes: Default, System, Light, Dark (case sensitive)
  BackdropPreference        = Mica    # available modes: Default, None, Mica, Acrylic, Tabbed
  ExtendFrameIntoClientArea = False   # enable to apply backdrop on background of apps (not recommended)
  EnableBlurBehind          = False   # make window translucent
}

# don't touch explorer and mspaint
Process: "explorer" {
  TitleBarColor = Dark
  BackdropPreference = Mica
  ExtendFrameIntoClientArea = True
  EnableBlurBehind = False
}
Process: "mspaint" {
  TitleBarColor = Default
  BackdropPreference = Mica
  ExtendFrameIntoClientArea = False
  EnableBlurBehind = False
}

# apply Mica background to Console Host window
Class: "ConsoleWindowClass" {
  TitleBarColor = System
  BackdropPreference = Mica
  ExtendFrameIntoClientArea = False
  EnableBlurBehind = False
}

Process: "ConEmu64" {
  TitleBarColor = Default
  BackdropPreference = Mica
  ExtendFrameIntoClientArea = False
  EnableBlurBehind = False
}

Process: "chrome" {
  TitleBarColor = Light
  BackdropPreference = Mica
  ExtendFrameIntoClientArea = False
  EnableBlurBehind = True
}

Process: "ONENOTE" {
  TitleBarColor = Default
  BackdropPreference = Mica
  ExtendFrameIntoClientArea = False
  EnableBlurBehind = False
}
```

**Comment by dongle-the-gadget** [comment]
Does this change anything?
```
Process: "chrome" {
  TitleBarColor = Default
  BackdropPreference = Default
  ExtendFrameIntoClientArea = False
  EnableBlurBehind = True
}
```

**Comment by HeyItsJono** [comment]
> Does this change anything?
> 
> ```
> Process: "chrome" {
>   TitleBarColor = Default
>   BackdropPreference = Default
>   ExtendFrameIntoClientArea = False
>   EnableBlurBehind = True
> }
> ```

Unfortunately not. Oddly, despite my Global Rules BackdropPref being set to Mica and Windows default set to Dark, when I use that config, Chrome's titlebars are plain white/Light as if I had the style set to None. If I then manually choose Mica for the chrome process rule, it turns blurred like my original post.

**Comment by dongle-the-gadget** [comment]
Unfortunately, there's not much we can do to help as MFE is basically a frontend to DWM APIs such as `SetWindowCompositionAttribute` and `DwmSetWindowAttribute`. Whether the backdrops are successfully drawn cannot be guaranteed by MFE, as it has no knowledge about the programs whatsoever.

**Comment by HeyItsJono** [comment]
No worries, thanks for your efforts

**Comment by bigplayer-ai** [comment]
Hey,
You found any solution for google chrome mica effect? It is very bad at my current settings :(
https://github.com/MicaForEveryone/MicaForEveryone/issues/231

**Comment by HeyItsJono** [comment]
Sorry, can't help you. I've since updated to Win 11's latest build and I use the acrylic rather than mica effect which is working normally for me. For the record, you can use MFE and chrome themes together with `-disable-windows10-custom-titlebar`, so my Chrome looks like this.

![image](https://user-images.githubusercontent.com/4620093/213900548-33763689-cb90-4e79-894e-8d7b57199e26.png)
