### ISSUE TITLE
Windows 11 HDR mode. Not showing text ?

### ISSUE THREAD

**Issue by Revolutionspop** [minusium/MicaForEveryone#61]

**Comment by dongle-the-gadget** [comment]
Can you provide a screenshot?

**Comment by Revolutionspop** [comment]
![20220408_084414](https://user-images.githubusercontent.com/103219876/162464267-775534d9-344a-40c9-82f0-0f058f6c3fa3.jpg)
![20220408_084211](https://user-images.githubusercontent.com/103219876/162464361-62d458ad-9163-4fb8-a8af-e5b5cab37ab3.jpg)

**Comment by dongle-the-gadget** [comment]
Did you have Blur Behind enabled?

**Comment by Revolutionspop** [comment]
The screen with text is with HDR off. It does the same with Mica, Arcylic, Tabbed settings  works great in SDR. I hope this might help. Thanks

**Comment by Revolutionspop** [comment]
Yes just a moment

**Comment by Revolutionspop** [comment]
![image](https://user-images.githubusercontent.com/103219876/162472952-630f0427-6006-4424-8ae5-4aeb977581ea.png)

**Comment by Revolutionspop** [comment]
it does the same thing with blur behind on and off

**Comment by dongle-the-gadget** [comment]
I would recommend disabling ExtendFrameIntoClientArea, and EnableBlurBehind.

**Comment by Revolutionspop** [comment]
Okay I will give it a try Boss. lol

**Comment by Revolutionspop** [comment]
![20220408_090300](https://user-images.githubusercontent.com/103219876/162469434-51c22bc3-51e3-4442-8d7e-7c20f0fd6bc1.jpg)

**Comment by dongle-the-gadget** [comment]
Can't see any changes.

**Comment by Revolutionspop** [comment]
Same thing is happening but I noticed when my arrow is over the text it shows up a little 
![20220408_094657](https://user-images.githubusercontent.com/103219876/162477825-b67aa7bb-932f-4717-82df-56f958701927.jpg)
![20220408_094735](https://user-images.githubusercontent.com/103219876/162477849-6374755f-2e4e-443d-bfed-206093140727.jpg)

**Comment by dongle-the-gadget** [comment]
How about disabling Extend Frame Into Client Area?

**Comment by Revolutionspop** [comment]
![image](https://user-images.githubusercontent.com/103219876/162480204-681c8d3c-cba4-48be-b60f-943e9fe2af5c.png)

**Comment by dongle-the-gadget** [comment]
Are text readable now?

**Comment by Revolutionspop** [comment]
![image](https://user-images.githubusercontent.com/103219876/162480481-a9170d25-dbb2-4eef-b50f-4d733995319f.png)

**Comment by Revolutionspop** [comment]
Yes with settings from pic above-mentioned

**Comment by dongle-the-gadget** [comment]
Btw https://github.com/minusium/MicaForEveryone/wiki/FAQ#window-doesnt-have-a-backdrop-background-after-enabling-extend-window-frame-into-client-area-or-its-not-rendering-correctly
