### ISSUE TITLE
How to add more than 1 app to config file

### ISSUE THREAD

**Issue by KibSquib48** [minusium/MicaForEveryone#7]
it seems like it's not possible to add more than one app to the config.ini, it keeps throwing up errors whenever I try to add more than one process name

**Comment by minusium** [comment]
Yes it's a known issue. I'm using IniParser library and I thought it allows to use multiple ini sections with same name but actually it doesn't. I have to implement my own parser, or fork their parser and add ability to have multiple section with same name, or use another format like json or xml.

**Comment by minusium** [comment]
Fixed by #8 
New release with fix is available: https://github.com/minusium/MicaForEveryone/releases/tag/v0.0.4.0
